### ISSUE TITLE
Missed opportunity to call it Toastify

### ISSUE THREAD

**Issue by MininMobile** [khanhas/ToastSpotify#1]
smh my head

**Comment by khanhas** [comment]
There is a [Toastify](https://github.com/nachmore/toastify) software already. 

![angery](https://media.discordapp.net/attachments/148103787259756544/458535183721693184/emoji_u1f611.png?width=703&height=703)

**Comment by MininMobile** [comment]
[@Toastify](https://github.com/nachmore/toastify) shut
